apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ratv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ratv
    app.kubernetes.io/part-of: byoc-app-wdva
  name: ratv
spec:
  rules:
  - host: ratv-byoc-tytd-tenant.apps.848cd6a9c5763fe656e1.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: ratv
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
